/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ResumeTemplateService } from "../resumeTemplate.service";
import { ResumeTemplateCreateInput } from "./ResumeTemplateCreateInput";
import { ResumeTemplate } from "./ResumeTemplate";
import { ResumeTemplateFindManyArgs } from "./ResumeTemplateFindManyArgs";
import { ResumeTemplateWhereUniqueInput } from "./ResumeTemplateWhereUniqueInput";
import { ResumeTemplateUpdateInput } from "./ResumeTemplateUpdateInput";
import { CommentFindManyArgs } from "../../comment/base/CommentFindManyArgs";
import { Comment } from "../../comment/base/Comment";
import { CommentWhereUniqueInput } from "../../comment/base/CommentWhereUniqueInput";
import { LikeFindManyArgs } from "../../like/base/LikeFindManyArgs";
import { Like } from "../../like/base/Like";
import { LikeWhereUniqueInput } from "../../like/base/LikeWhereUniqueInput";
import { PurchaseHistoryFindManyArgs } from "../../purchaseHistory/base/PurchaseHistoryFindManyArgs";
import { PurchaseHistory } from "../../purchaseHistory/base/PurchaseHistory";
import { PurchaseHistoryWhereUniqueInput } from "../../purchaseHistory/base/PurchaseHistoryWhereUniqueInput";

export class ResumeTemplateControllerBase {
  constructor(protected readonly service: ResumeTemplateService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ResumeTemplate })
  async createResumeTemplate(
    @common.Body() data: ResumeTemplateCreateInput
  ): Promise<ResumeTemplate> {
    return await this.service.createResumeTemplate({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        industry: true,
        profession: true,
        fileWord: true,
        filePdf: true,
        freeDownload: true,
        price: true,
        author: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ResumeTemplate] })
  @ApiNestedQuery(ResumeTemplateFindManyArgs)
  async resumeTemplates(
    @common.Req() request: Request
  ): Promise<ResumeTemplate[]> {
    const args = plainToClass(ResumeTemplateFindManyArgs, request.query);
    return this.service.resumeTemplates({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        industry: true,
        profession: true,
        fileWord: true,
        filePdf: true,
        freeDownload: true,
        price: true,
        author: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ResumeTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async resumeTemplate(
    @common.Param() params: ResumeTemplateWhereUniqueInput
  ): Promise<ResumeTemplate | null> {
    const result = await this.service.resumeTemplate({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        industry: true,
        profession: true,
        fileWord: true,
        filePdf: true,
        freeDownload: true,
        price: true,
        author: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ResumeTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateResumeTemplate(
    @common.Param() params: ResumeTemplateWhereUniqueInput,
    @common.Body() data: ResumeTemplateUpdateInput
  ): Promise<ResumeTemplate | null> {
    try {
      return await this.service.updateResumeTemplate({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          industry: true,
          profession: true,
          fileWord: true,
          filePdf: true,
          freeDownload: true,
          price: true,
          author: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ResumeTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteResumeTemplate(
    @common.Param() params: ResumeTemplateWhereUniqueInput
  ): Promise<ResumeTemplate | null> {
    try {
      return await this.service.deleteResumeTemplate({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          industry: true,
          profession: true,
          fileWord: true,
          filePdf: true,
          freeDownload: true,
          price: true,
          author: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/comments")
  @ApiNestedQuery(CommentFindManyArgs)
  async findComments(
    @common.Req() request: Request,
    @common.Param() params: ResumeTemplateWhereUniqueInput
  ): Promise<Comment[]> {
    const query = plainToClass(CommentFindManyArgs, request.query);
    const results = await this.service.findComments(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        content: true,
        author: true,

        resumeTemplate: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/comments")
  async connectComments(
    @common.Param() params: ResumeTemplateWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        connect: body,
      },
    };
    await this.service.updateResumeTemplate({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/comments")
  async updateComments(
    @common.Param() params: ResumeTemplateWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        set: body,
      },
    };
    await this.service.updateResumeTemplate({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/comments")
  async disconnectComments(
    @common.Param() params: ResumeTemplateWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        disconnect: body,
      },
    };
    await this.service.updateResumeTemplate({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/likes")
  @ApiNestedQuery(LikeFindManyArgs)
  async findLikes(
    @common.Req() request: Request,
    @common.Param() params: ResumeTemplateWhereUniqueInput
  ): Promise<Like[]> {
    const query = plainToClass(LikeFindManyArgs, request.query);
    const results = await this.service.findLikes(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        resumeTemplate: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/likes")
  async connectLikes(
    @common.Param() params: ResumeTemplateWhereUniqueInput,
    @common.Body() body: LikeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      likes: {
        connect: body,
      },
    };
    await this.service.updateResumeTemplate({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/likes")
  async updateLikes(
    @common.Param() params: ResumeTemplateWhereUniqueInput,
    @common.Body() body: LikeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      likes: {
        set: body,
      },
    };
    await this.service.updateResumeTemplate({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/likes")
  async disconnectLikes(
    @common.Param() params: ResumeTemplateWhereUniqueInput,
    @common.Body() body: LikeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      likes: {
        disconnect: body,
      },
    };
    await this.service.updateResumeTemplate({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/purchaseHistories")
  @ApiNestedQuery(PurchaseHistoryFindManyArgs)
  async findPurchaseHistories(
    @common.Req() request: Request,
    @common.Param() params: ResumeTemplateWhereUniqueInput
  ): Promise<PurchaseHistory[]> {
    const query = plainToClass(PurchaseHistoryFindManyArgs, request.query);
    const results = await this.service.findPurchaseHistories(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        pricePaid: true,
        paymentMethod: true,

        resumeTemplate: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/purchaseHistories")
  async connectPurchaseHistories(
    @common.Param() params: ResumeTemplateWhereUniqueInput,
    @common.Body() body: PurchaseHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      purchaseHistories: {
        connect: body,
      },
    };
    await this.service.updateResumeTemplate({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/purchaseHistories")
  async updatePurchaseHistories(
    @common.Param() params: ResumeTemplateWhereUniqueInput,
    @common.Body() body: PurchaseHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      purchaseHistories: {
        set: body,
      },
    };
    await this.service.updateResumeTemplate({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/purchaseHistories")
  async disconnectPurchaseHistories(
    @common.Param() params: ResumeTemplateWhereUniqueInput,
    @common.Body() body: PurchaseHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      purchaseHistories: {
        disconnect: body,
      },
    };
    await this.service.updateResumeTemplate({
      where: params,
      data,
      select: { id: true },
    });
  }
}
